Study_Project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Study_Project import settings

urlpatterns = [
    path('', include('base.urls')),
    path('accounts/', include('account.urls')),
    path('words/', include('new_words.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/urls.py
from django.urls import path

from . import views


app_name = 'base'

urlpatterns = [
    path('', views.main_page, name='main_page'),
    path('trainer/', views.trainer, name='trainer'),
    path('section_in_development/', views.section_in_development, name='section_in_development'),
]

new_words/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views


app_name = 'words'

urlpatterns = [
    # API
    path('api/words/', views.WordsAPIView.as_view()),
    path('api/train-object/', views.TrainObjectAPIView.as_view()),
    path('api/get-variants/<int:number_variants>/', views.get_possible_variants),
    path('api/words/', views.WordsAPIView.as_view(), name='words'),
    path('api/words/<int:pk>/', views.WordDetailApiView.as_view(), name='words_detail'),
    path('api/add-word-to-train/', views.AddWordToTrain.as_view(), name='add_word_to_train'),

    # Trainer
    path('words-text/', views.words_text, name='words_text'),
    path('words-with-variants/', views.words_with_variants, name='words_with_variants'),

    # DB
    path('add-new-word/', views.add_word, name='add_word'),
    path('words-review/', views.WordsReviewView.as_view(), name='words_review'),

    # Trains management
    path('trains/change-status/<int:train_id>/', views.change_train_status, name='change_train_status'),
    path('trains/increase-attempt-counter/<int:train_id>/<is_right>/', views.increase_attempt_counter, name='increase_attempt_counter')
]

base/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from services import account_funcs


def main_page(request):
    context = {}
    if request.user.is_authenticated:
        context.update(account_funcs.get_user_words_statistic(request.user))
    return render(request, 'base/main_page.html', context=context)


@login_required
def trainer(request):
    return render(request, 'base/trainer.html')


def section_in_development(request):
    return render(request, 'base/section_in_development.html')

base/templates/base/base.html
{% load static %}
{% load random_numbers %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}?n={% random_int %}">
    <link rel="stylesheet" href="{% static 'base/css/base_adaptive.css' %}?n={% random_int %}">
    {% block css_links %} {% endblock css_links %}
</head>
<body>
    <div class="header">
        <div class="header-logo">
            <img src="/static/base/img/81_logo.png" alt="StudyEnglish">
        </div>
        <nav>
            <a href="{% url 'base:main_page' %}" class="nav-link">Главная</a>
            <a href="{% url 'base:trainer' %}" class="nav-link">Тренажер</a>

            {% if request.user.is_authenticated %}
                <a href="{% url 'personal_page' %}" class="nav-link">Мой аккаунт</a>
                {% if request.user.username == 'admin' %}
                    <a href="/admin/" class="nav-link">Админка</a>
                    <a href="{% url 'words:add_word' %}" class="nav-link">Новое слово</a>
                {% endif %}
            {% else %}
                <a href="{% url 'login' %}" class="nav-link">Войти</a>
            {% endif %}

        </nav>

        <div class="burger-menu-btn">
            <div class="burger-menu-line"></div>
            <div class="burger-menu-line"></div>
            <div class="burger-menu-line"></div>
        </div>

        <div class="burger-menu-nav">
            <a href="{% url 'base:main_page' %}" class="nav-link">Главная</a>
            <a href="{% url 'base:trainer' %}" class="nav-link">Тренажер</a>

            {% if request.user.is_authenticated %}
                <a href="{% url 'personal_page' %}" class="nav-link">Мой аккаунт</a>

                {% if request.user.username == 'admin' %}
                    <a href="/admin/" class="nav-link">Админка</a>
                    <a href="{% url 'words:add_word' %}" class="nav-link">Новое слово</a>
                {% endif %}

            {% else %}
                <a href="{% url 'login' %}" class="nav-link">Войти</a>
            {% endif %}
        </div>
    </div>

    <!--  BURGER MENU  -->
    <script>
        let btn = document.querySelector(".burger-menu-btn")
        let burgerNav = document.querySelector(".burger-menu-nav")
        function switchClass() {
            btn.classList.toggle('active')
            burgerNav.classList.toggle('active')
        }
        btn.addEventListener('click', switchClass)
    </script>

    <!--  Page sizes  -->
    <script>

    </script>


    <div class="content-area">
        {% block page_content %} {% endblock page_content %}
    </div>

</body>
</html>

base/templates/base/main_page.html
{% extends 'base/base.html' %}
{% load static %}
{% load random_numbers %}


{% block title %}
    Главная
{% endblock title %}

{% block css_links %}
    <link rel="stylesheet" href="{% static 'base/css/main_page.css' %}?n={% random_int %}">
{% endblock css_links %}

{% block page_content %}

    {% if request.user.is_authenticated %}
        <div class="container">
            <h1>Ваш прогресс:</h1>
            <h2>Изучено слов - {{ studied }}</h2>
            <h2>Слов на изучении - {{ on_study }}</h2>
        </div>
        <div class="container">
            <p><a href="{% url 'words:words_text' %}?&mode=study&lang=en-ru" class="train-btn">Изучить слова</a></p>
            <p><a href="{% url 'words:words_text' %}?&mode=repeat&lang=en-ru" class="train-btn">Повторить слова</a></p>
        </div>
    {% else %}
        <div class="container">
            <h2>Присоединяйтесь!</h2>
            <a href="{% url 'login' %}">Войти</a>
            или
            <a href="{% url 'register' %}">Зарегистрироваться</a>
        </div>
    {% endif %}

{% endblock page_content %}

base/templates/base/section_in_development.html
{% extends 'base/base.html' %}
{% load static %}
{% load random_numbers %}


{% block title %}
    Страница в разработке
{% endblock title %}

{% block css_links %}
{% endblock css_links %}

{% block page_content %}
    <h1>Страница в разработке...</h1>
{% endblock page_content %}

base/templates/base/trainer.html
{% extends 'base/base.html' %}
{% load static %}
{% load random_numbers %}


{% block title %}
    Тренажер
{% endblock title %}

{% block css_links %}
    <link rel="stylesheet" href="{% static 'base/css/trainer.css' %}?n={% random_int %}">
    <link rel="stylesheet" href="{% static 'base/css/trainer_adaptive.css' %}?n={% random_int %}">
{% endblock css_links %}

{% block page_content %}
    <div class="container">

        <div class="add-words-btn">
            <a href="{% url 'words:words_review' %}" class="button">Открыть список слов</a>
        </div>
    
        <div class="box">
            <div class="box-container">
                <div class="vertical-flexbox">
                    <h3>Изучить слова</h3>
                    <a class="train-btn" href="{% url 'words:words_text' %}?&mode=study&lang=en-ru">EN --> RU</a>
                    <a class="train-btn" href="{% url 'words:words_text' %}?&mode=study&lang=ru-en">RU --> EN</a>
                    <a class="train-btn" href="{% url 'words:words_with_variants' %}?&mode=study&lang=en-ru">С вариантами <br> EN --> RU</a>
                    <a class="train-btn" href="{% url 'words:words_with_variants' %}?&mode=study&lang=ru-en">С вариантами <br> RU --> EN</a>
                </div>
            </div>
    
            <div class="box-container">
                <div class="vertical-flexbox">
                    <h3>Повторить слова</h3>
                    <a class="train-btn" href="{% url 'words:words_text' %}?&mode=repeat&lang=en-ru">EN --> RU</a>
                    <a class="train-btn" href="{% url 'words:words_text' %}?&mode=repeat&lang=ru-en">RU --> EN</a>
                </div>
            </div>
        </div>
    </div>
{% endblock page_content %}